version: '3'
services:
  app:
    container_name: adloid-project
    image: adloid-project:v1
    build: .
    links:
      - "redis"
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/redis:/adloid-service/logs
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6380:6379"
