version: '3'
services:
  app:
    container_name: spring-redis-project
    image: spring-redis-project:v1
    build: .
    links:
      - "redis"
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/redis:/spring-app/logs
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6380:6379"
